version: "3.9"
services:
  panel:
    build: .
    image: panel
    container_name: panel
    env_file:
      - .env
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - mukhtaser_mukhtaser_net
networks:
  mukhtaser_mukhtaser_net:
